pipelines:
  - name: test
    steps:     
      - name: triggerAG1
        type: Bash
        execution:
          onExecute:
            - echo "Hello World"
  
      - name: triggerAG2
        type: Bash
        configuration:
          inputSteps:
            - name: triggerAG1
              status:
                - success
        execution:
          onExecute:
            - echo "Hello World"
  
      - name: Approval_gate
        type: Bash
        configuration:
          inputSteps:
            - name: triggerAG2
              status:
                - success
          requiresApproval: false
#             approvers:
#               - neham
            notifications:
              - integrationName: slack
        execution:
          onExecute:
            - echo "Hello World"
