
resources:
  - name: cr
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *' # Every 5 mins

pipelines:
  - name: testcron_pipeline
    steps:
      - name: basicTest
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: cr
        execution:
          onExecute:
            - echo hi
