resources:
 - name: resource_pipelines1245
   type: GitRepo
   configuration:
     gitProvider: github_neha
     path: neha-mishraa/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        pullRequestCreate: true
#      cancelPendingRunsOn:
#        pullRequestUpdate: true

pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines1245
         integrations:
           - name: github_neha
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - echo "hi"
          onSuccess:
            - pushd $res_resource_pipelines1245_resourcePath
            - ls



      
