resources:
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: github_neha
      path: neha-mishraa/pipelines
      buildOn:
         commit: true
pipelines:
  - name: testPipelineRel
    steps:
      - name: testStep
        type: Bash
        configuration:
          inputResources:
            - name: gitresource
        execution:
           onStart:
            - echo "executing onStart"
           onExecute:
             - echo "executing onExecute"
             - echo "executing onExecute"
             - pushd $res_gitresource_resourcePath
