resources:
  - name: gitresourcenm
    type: GitRepo
    configuration:
      gitProvider: github_neha
      path: neha-mishraa/pipelines
      buildOn:
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
pipelines:
  - name: testPipelineRel
    steps:
      - name: testStep
        type: Bash
        configuration:
          inputResources:
            - name: gitresourcenm
        execution:
           onStart:
            - echo "executing onStart"
           onExecute:
             - echo "executing onExecute"
             - pushd $res_gitresource_resourcePath
