resources:
  - name: git
    type: gitRepo
    configuration:
      gitProvider: github_integration  
      path: codecode10/pipelines
pipelines:
  - name: my_pipeline
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: git
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
          onSuccess:
            - echo "executing onSuccess"
          onFailure:
            - echo "executing onFailure"
          onComplete: 
            - echo "executing onComplete"   
