pipelines:
  - name: testPipeline
    steps:
      - name: testStepBash
        type: Bash
        configuration:
          nodePool: dynamicGCP
        execution:
          onExecute:
            - echo "hello"
