pipelines:
  - name: testDynamicPool
    configuration:
      nodePool: dynamic_azure
    steps:
      - name: testBashStep
        type: Bash       
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - sleep 20s
