pipelines:
  - name: test_DynamicPool
    configuration:
      nodePool: test_u18
    steps:
      - name: testBashStep
        type: Bash       
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - sleep 20s
