# resources:
#   - name: git_resc
#     type: gitRepo
#     configuration:
#       gitProvider: github_neha
#       path: neha-mishraa/pipelines

####################################
pipelines:
  - name: testpipeline
#     configuration:
#       nodePool: u16StaticNP
    steps:
      - name: testStep
        type: Bash
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
            - sleep 5s

####################################
# pipelines:
#   - name: pipeline_S_PS
#     steps:
#       - name: S_PS
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#         execution:
# #           onExecute:
# #             - java --version
#           onFailure:
#             - write-output "Job well done!"


#             - printenv
#       - name: testStep2
#         type: Bash
#         configuration:
#           runtime:
#             type: host
#           inputSteps:
#             - name: testStep
#         execution:
#           onStart:
#             - echo "executing onStart"
#           onExecute:
#             - echo "executing onExecute"
#             - sleep 5s
#             - fallocate -l 10G huge_file.dat
#             - df -h
#             - fallocate -l 10G huge_file.dat1
#             - df -h
#             - fallocate -l 7G huge_file.dat2
#             - df -h
            
            
#             - fallocate -l 7G huge_file.dat3
#             - df -h
#             - fallocate -l 10G huge_file.dat4
#             - df -h

#       - name: testStepBash1
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: testStep
#         execution:
#           onStart:
#             - echo "executing onStart"
#           onExecute:
#             - echo "executing onExecute"
#             - sleep 5s
#       - name: testStepBash2
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: testStep
#         execution:
#           onStart:
#             - echo "executing onStart"
#           onExecute:
#             - echo "executing onExecute"
#             - sleep 5s
#       - name: testStepBash3
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: testStep
#         execution:
#           onStart:
#             - echo "executing onStart"
#           onExecute:
#             - echo "executing onExecute"
#             - sleep 5s
