resources:
  - name: git_resc
    type: gitRepo
    configuration:
      gitProvider: github_neha
      path: neha-mishraa/pipelines
pipelines:
  - name: testpipeline
    configuration:
      nodePool: k8_dynamic
    steps:
      - name: testStep
        type: Bash
        configuration:
          inputResources:
            - name: git_resc
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
