pipelines:
  - name: pipelines_NP_DyGCP
    steps:
      - name: NP_DyGCP_0041
        type: Bash
        configuration:
          nodePool: dynamic_gcp
        execution:
          onExecute:
            - echo "hi"
