# resources:
#   - name: git_resc
#     type: gitRepo
#     configuration:
#       gitProvider: github_neha
#       path: neha-mishraa/pipelines
pipelines:
  - name: testpipeline
#     configuration:
#       nodePool: K8NP
    steps:
      - name: testStep
        type: Bash
#         configuration:
#           inputResources:
#             - name: git_resc
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
            - sleep 20
            - df -h
            - fallocate -l 10G huge_file.dat
            - df -h
            - fallocate -l 10G huge_file.dat1
            - df -h
            - fallocate -l 5G huge_file.dat2
            - df -h
            - fallocate -l 7G huge_file.dat3
            - df -h
            - fallocate -l 10G huge_file.dat4
            - df -h
