pipelines:
  - name: NP_DyGCP
    steps:
      - name: NP_DyGCP_41
        type: Bash
        configuration:
          nodePool: dynamic_gcp
        execution:
          onExecute:
            - echo "hello"
