pipelines:
  - name: testpipeline
#     configuration:
#       nodePool: u16dynamic
    steps:
      - name: testStep
        type: Bash
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
            - sleep 5s
            - df -h 
            - fallocate -l 10G huge_file.dat
            - df -h
            - fallocate -l 10G huge_file.dat1
            - df -h
            - fallocate -l 5G huge_file.dat2
            - df -h
            - fallocate -l 5G huge_file.dat2
            - df -h
            - fallocate -l 5G huge_file.dat3
            - df -h
            - fallocate -l 3aG huge_file.dat3
            - df -h
#             - fallocate -l 10G huge_file.dat4
#             - df -h
