pipelines:
  - name: testPipeline
    configuration:
      nodePool: k8_dynamic
    steps:
      - name: testBashStep
        type: Bash 
        configuration:
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing step.."
