template: true
valuesFilePath: ./values.yml

resources:
 - name: connecting_resource_node_test
   type: PropertyBag
   configuration:
     key1: value1
     key2: value2
 - name: resource_pipelines
   type: GitRepo
   configuration:
     gitProvider: agrasth
     path: agrasth/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        commit: true

pipelines:
  - name: pipelines_node_test
    steps:
      - name: trigger_node_test
        type: Bash
        configuration:
          outputResources: 
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - write_output connecting_resource_node_test "test=value"
      {{- range $nodePoolProperty := .Values.nodePoolProperty }}
      - name: pipe_step_{{ $nodePoolProperty.name }}
        type: {{ $nodePoolProperty.type }}
        configuration:
          nodePool: {{ $nodePoolProperty.name }}
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - docker images
      {{- end}}
