resources:
 - name: resource_pipelines
   type: GitRepo
   configuration:
     gitProvider: github_neham
     path: neha-mishraa/pipelines
     files: 
       include: .* #^README.md$
     branches:
       include: master #^{{gitBranch}}$
     buildOn:
       commit: true

pipelines:
  - name: testing
    steps:
      - name: myStep
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines
         integrations:
           - name: github_neham
#            - name: slackTest
        execution:
          onExecute:
#             - printenv
            - pushd $res_resource_pipelines_resourcePath
            - ls
            - echo "hi"
#             - send_notification slackTest --text "Pipeline test"
          onSuccess:
            - pushd $res_resource_pipelines_resourcePath
            - ls
