pipelines:
  - name: demoPipeline
    steps:
      - name: demoStep
        type: Bash
        execution:
          onStart:
            - export_pipeline_variables
            - |
              if [[ "$currentStatus" == "processing" ]]; then
                echo "wait for sometime"
                n=0 #starting value
                max=5 #max-retries
                until [ "$n" -ge "$max" ]
                do
                  export_pipeline_variables
                  if [[ "$currentStatus" == "completed" ]] && break
                  n=$((n+1)) 
                  sleep 15
                done
              else
                add_pipeline_variables currentStatus="processing"
              fi
          onExecute: 
            - echo "Steps to be executed"
          onComplete:
            - add_pipeline_variables currentStatus="completed"
