pipelines:
  - name: demoCurlPipeline
    steps:
       - name: curlStep
         type: Bash
         configuration:
           integrations:
             - name: test_artifactory
         execution:
           onStart:
             - echo "================= Adding helm cli ====================================="
             # - curl -sSL -vv -H "X-JFrog-Download-Redirect-To:pdn" -o helm.tar.gz https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
             - curl -vv -H "X-JFrog-Download-Redirect-To:pdn" -u admin:password https://pdnpp.jfrogdev.org/artifactory/example-repo-local/progit-2.0.0.pdf -o progit-2.0.0.pdf
             - ls -la
             # - tar xzvf helm.tar.gz
