pipelines:
  - name: demoPipeline
    steps:
       - name: demoStep
         type: Bash
         configuration:
           integrations:
             - name: test_artifactory
         execution:
           onStart:
             - export_pipeline_variables
             - |
               if [[ "$currentStatus" == "processing" ]]; then
                 echo "wait for sometime"
               else
                 add_pipeline_variables currentStatus="processing"
               fi
           onExecute: 
             - echo "Steps to be executed"
           onComplete:
             - add_pipeline_variables currentStatus="completed"
